services:
  - type: web
    name: BlogSpot
    env: python
    buildCommand: " pip install -r requirements.txt"
    startCommand: gunicorn --chdir blogspot blogspot.wsgi
    preDeployCommand: |
      python manage.py migrate
      python manage.py collectstatic --noinput
      python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); if not User.objects.filter(username='admin').exists(): User.objects.create_superuser('admin', 'admin@gmail.com', 'Admin@123')"
