databases:
  - name: blogspot-db
    databaseName: blogspot
    user: blogspot_user

services:
  - type: web
    name: BlogSpot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --chdir blogspot blogspot.wsgi"
    preDeployCommand: |
      python manage.py migrate
      python manage.py collectstatic --noinput
      python manage.py shell -c "from django.contrib.auth import get_user_model; User = get_user_model(); if not User.objects.filter(username='admin').exists(): User.objects.create_superuser('admin', 'admin@gmail.com', 'Admin@123')"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: blogspot-kzgs.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: blogspot-db
          property: connectionString
      - key: DJANGO_ENV
        value: production
      - key: CLOUDINARY_CLOUD_NAME
        value: dajeitt4m
      - key: CLOUDINARY_API_KEY
        value: 443843417917178
      - key: CLOUDINARY_API_SECRET
        value: 4B5IyUFtIbvZJjEfTozH5t0gi7I